import React from 'react';
import './faq.scss';
import FaqItem from './FaqItem';

const FAQ = [
    {
        title: 'WHAT IS THE AFFILIATE PROGRAM?',
        desc: 'The affiliate program works like a commission based system, based on sales of services through entertainment products. The Betvili online merchant offers its services via its affiliate partners, through the Betvili Partners program, with which he subsequently shares the profit made - generated by player losses - from betvili.com. In the particular case of the Betvili Partners program, the commission – "affiliate "- partner brings his visitors to the betvili.com site, and then receives his monthly commission payment generated by new customers he has referred on betvili.com.'
    },
    {
        title: 'WHY SHOULD I REGISTER ON THE AFFILIATE PROGRAM?',
        desc: 'There are many reasons to register in our affiliate program. It is free of charge, offers high revenue share, plenty of products, so why not monetize your traffic with Betvili Partners today'
    },
    {
        title: 'WHO CAN REGISTER IN THE AFFILIATE PROGRAM?',
        desc: 'Every person/webmaster operating their own web site(s) while respecting our general terms and conditions can join Betvili Partners . Each affiliate partner may only register once.'
    },
    {
        title: 'ARE THERE ANY JOINING FEES TO BE ASSOCIATED WITH BETVILI PARTNERS ?',
        desc: 'Joining Betvili Partners is completely free! There are no charges at all.'
    },
    {
        title: 'HOW DO I REGISTER TO BECOME A MEMBER OF BETVILI PARTNERS ?',
        desc: 'Signing up to Betvili Partners is easy! Simply click on REGISTER button and fill in the form to become a member of Betvili Partners .'
    },
    {
        title: 'CAN I REGISTER MORE THAN ONE WEBSITE?',
        desc: 'Yes, you can. If your application is successful you can register multiple websites in your Betvili Partners account. You can create individual tracking links for each site so you can track their performances.'
    },
    {
        title: 'DOES BETVILI PARTNERS ACCEPT ALL WEBSITES?',
        desc: 'Signing up to Betvili Partners is easy! Simply click on REGISTER button and fill in the form to become a member of Betvili Partners.'
    },
    {
        title: 'CAN I BECOME AN AFFILIATE EVEN IF I DON’T HAVE MY OWN WEBSITE?',
        desc: 'Yes, you can. We provide alternative tools that you can use to promote betvili.com. Contact our affiliate managers today at affiliates@betvili.com to discuss the options available for you!'
    },
    {
        title: 'HOW MUCH CAN I EARN?',
        desc: 'There is no limit to the amount of revenue you can earn. The more effort you put in to sending quality traffic, the more you earn.'
    },
    {
        title: 'CAN I PROMOTE BETVILI PARTNERS AND GET COMMISSIONS FROM REFERRING NEW AFFILIATES?',
        desc: 'Yes, you can refer a sub-affiliate and get additional earnings for every customer that your sub-affiliate sends to betvili.com.'
    },
    {
        title: 'HOW ARE COMMISSIONS CALCULATED?',
        desc: 'Your monthly commission is the percentage of the Net Revenue generated by your referred players. Net Revenue is calculated as the total GGR(Bets-Wins) less direct costs associated with the same referrals, such as bonuses, game provider fees, loyalty rewards, transaction fees, and chargebacks/refunds.'
    },
    {
        title: 'HOW DO I GET THE COMMISSIONS?',
        desc: "Betvili Partners calculates commissions at the beginning of each month for the previous month's activity and transfers the commission within the first 2 weeks of each month."
    },
    {
        title: 'DO NEGATIVE BALANCES CARRY OVER?',
        desc: "We offer no negative carryover policy. For example, if your earnings are negative for the month of January, due to the client's big win, and in February it stays negative, from March you will start from 0."
    },
    {
        title: 'HOW CAN I CLOSE MY ACCOUNT?',
        desc: 'To close your Betvili Partners account, send an email request to affiliates@betvili.com. Please ensure that you provide us with your affiliate ID, your first and last name.'
    },
    {
        title: 'HOW CAN I CONTACT YOU?',
        desc: 'You can contact us anytime by this email: affiliates@betvili.com.'
    }
]

const Faq = () => {
    return (
        <div className='con-6'>
        <div className='faq-section'>
          <div className='faq-item-wrap'>
            <div className='faq-header'>FAQ</div>
            {FAQ.map((item, index) => (
              <FaqItem key={index} item={item} index = {index}/>
            ))}
          </div>
        </div>
      </div>
    );
};

export default Faq;